# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: postgres
  database: mstarcosmic_development

test:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: postgres
  password: postgres
  database: mstarcosmic_test

production:
  primary:
    <<: *default
    adapter: postgresql
    # encoding: unicode
    pool: 5
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *default
    adapter: postgresql
    database: <%= ENV['CACHE_DATABASE_URL'] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    adapter: postgresql
    database: <%= ENV['QUEUE_DATABASE_URL'] %>
    migrations_paths: db/queue_migrate  
  cable:
    <<: *default
    adapter: postgresql
    url: <%= ENV['CABLE_DATABASE_URL'] %>

