require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.


  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  # config.action_mailer.raise_delivery_errors = false
  
  config.action_mailer.perform_caching = false
  config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }
  config.action_mailer.raise_delivery_errors = false
  config.action_mailer.delivery_method = :test

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
  config.hosts.clear
  config.action_dispatch.allow_browser = ->(user_agent) { true }

  # intake.localhost をサブドメインとして認識させる（開発環境のみ）。
  #
  # Rails は subdomain を「ホスト名から末尾 tld_length + 1 個の要素を除いた残り」として
  # 求める。既定の tld_length = 1 だと "intake.localhost" は要素が2つしかないため
  # 残りが空になり、subdomain が "" と判定される。その結果 routes.rb の
  # constraints(subdomain: "intake") が一致せず、開発環境では intake 画面に
  # 一切到達できない（/s/:token が 404 になる）。
  #
  # tld_length = 0 にすると "intake.localhost" → "intake" と正しく解釈される。
  # "localhost" 単体は要素が1つなので subdomain は "" のままで、既存画面に影響しない。
  #
  # 本番の "intake.mstarcosmic.com" は要素が3つあるため既定値のままで "intake" と
  # 判定される。したがってこの設定は development に閉じており、production では不要。
  config.action_dispatch.tld_length = 0
end
